# -*- coding: utf-8 -*-
"""QError.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FTrzRpR5ho7btZg4Ww6-e6GLLGslcXKu
"""

import sys
import numpy as np
from numpy.random import seed
import math
seed(12)

def qerror(k, X, y):
  res = 0
  for i in range(1, k+1):
    a = []
    for index in range(len(y)):
      if(y[index] == i):
        a.append(X[index])
    a_su = sum(a)
    a_mean = a_su/max(len(a), 1)
    dist = []
    for j in a:
      dist.append((j-a_mean)**2)
    for d in dist:
      res += sum(d)
  return res

if __name__ == "__main__":
  X = np.loadtxt('./iris-data.csv', delimiter=',')
  y = np.loadtxt('./iris-labels.csv', delimiter=',')
  print("Quantization error: ", qerror(3, X, y))

